name: Android CI

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v6

            -   name: set up JDK 17
                uses: actions/setup-java@v5
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Add empty keystore.properties
                run: |
                    echo "storePassword=dummy" > keystore.properties
                    echo "keyPassword=dummy" > keystore.properties
                    echo "keyAlias=dummy" > keystore.properties
                    echo "storeFile=dummy.jks" > keystore.properties

            -   name: Assemble Debug with Gradle
                run: ./gradlew assembleDebug

            -   name: Bundle Debug with Gradle
                run: ./gradlew bundleDebug

            -   name: Upload Artifact
                uses: actions/upload-artifact@v6
                with:
                    name: Debug APKs
                    path: app/build/outputs/apk/
                    retention-days: 30
